#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/libexec/dashboard-collector.sh

start_service() {
	procd_open_instance "main"
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	return 0
}
